targets:
  krpc_dart:
    builders:
      krpc_dart|KrpcServicesFetcher:
        options:
          'connected': true
          'ip': '192.168.0.149'
          'rpcPort': 50000

builders:
  KrpcServicesFetcher:
    import: 'package:krpc_dart/krpc_dart.dart'
    builder_factories: [ 'fetchKrpcServices' ]
    build_extensions:
      .dummy:
        - .json
    build_to: source
    auto_apply: root_package

  KrpcLibBuilder:
    import: 'package:krpc_dart/krpc_dart.dart'
    builder_factories: [ 'buildKrpcLib' ]
    build_extensions:
      .json:
        - .dart
    build_to: source
    auto_apply: root_package
    required_inputs:
      - '.json'
