targets:
  $default:
    builders:
      krpc_dart|buildKrpcLib:
        enabled: True

builders:
  buildKrpcLib:
    import: 'package:krpc_dart/krpc_dart.dart'
    builder_factories: ['buildKrpcLib']
    build_extensions:
      .dummy:
        - .dart
    build_to: source
    auto_apply: root_package

