targets:
  krpc_dart:
    builders:
      krpc_dart|KrpcLibBuilder:
        options:
          'connected': false
          'ip': 'localhost'
          'rpcPort': 50000


builders:
  KrpcLibBuilder:
    import: 'package:krpc_dart/krpc_dart.dart'
    builder_factories: [ 'buildKrpcLib' ]
    build_extensions:
      .dummy:
        - .json
        - .dart
    build_to: source
    auto_apply: root_package
