targets:
  $default:
    builders:
      krpc_dart|KrpcApiBuilder:
        enabled: true

builders:
  krpc_dart|KrpcApiBuilder:
    import: "package:krpc_dart/krpc_dart.dart"
    builder_factories: ["invokeBuilder"]
    build_extensions: {".krpc.json": [".dart"]}
    auto_apply: root_package
    build_to: source