name: krpc_dart
description: A library for Kerbal Space Program kRPC server
version: 0.1.0

repository: 'https://github.com/Inveniemus/krpc_dart/tree/develop_v0.1'

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  web_socket_channel: ^1.1.0
  protobuf: ^1.1.0
  meta: ^1.2.4
  # krpc protobuf dependency
  fixnum: ^0.10.11
  # Services extraction script dependencies:
  yaml: 2.2.1

dev_dependencies:
  lint: ^1.5.1
  test: ^1.15.7
