name: krpc_dart
description: A library to interact with kRPC internal server of Kerbal Space Program! Use it to develop Dart script or Flutter apps!
version: 0.2.0+1

repository: 'https://github.com/Inveniemus/krpc_dart/tree/develop_v0.2'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  web_socket_channel: ^2.1.0
  protobuf: ^2.0.0
  meta: ^1.4.0
  # krpc protobuf dependency
  fixnum: ^1.0.0
  # Services extraction script dependencies:
  yaml: ^3.1.0
  # Builder dependencies
  recase: ^4.0.0
  mustache_template: ^2.0.0
  bloc: ^7.0.0
  bloc_test: ^8.0.1
  equatable: ^2.0.2

dev_dependencies:
  test: ^1.17.5
