name: krpc_dart
description: A library to interact with kRPC internal server of Kerbal Space Program! Use it to develop Dart script or Flutter apps!
version: 0.2.0+1

repository: 'https://github.com/Inveniemus/krpc_dart/tree/develop_v0.2'

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  web_socket_channel: ^1.1.0
  protobuf: ^1.1.0
  meta: ^1.2.4
  # krpc protobuf dependency
  fixnum: ^0.10.11
  # Services extraction script dependencies:
  yaml: ^2.2.1
  # Builder dependencies
  recase: ^3.0.1
  mustache_template: ^1.0.0+1

dev_dependencies:
  test: ^1.15.7
