name: krpc_dart
description: The library for kRPC
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  web_socket_channel: ^1.1.0
  protobuf: ^1.1.0
  mustache_template: ^1.0.0+1
  recase: 3.0.0
  fixnum: ^0.10.11
  build: ^1.5.0
  logging: ^0.11.4
  mockito: ^4.1.3

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.5
  build_runner: ^1.10.4
